### ISSUE TITLE
how about add "Parameter Addition" function

### ISSUE THREAD

**Issue by Conanjun** [simioni87/auth_analyzer#10]
Hello Simioni87,nice to meet u !!!
    I have used auth_analyzer for a long time and it is really a great burp extension for pentersters ! ! ! But i have a problem that why not add the "Parameter Addition" function because u have realized the function of "Parameter Replacement". There are sevel scene for this addition function,such as hidden debug mode,for example some developper like to add "debug=1" in request(url post-param json-param etc) when write code but delete it in frontend,but the debug mode still exist and sometime it may cause some problem. In this scene, auth-analyzer can't add Parameter when origin request is not existed a parameter named "debug" so i have to  add it in processhttpmessage before auth-analyzer's code. Perhaps u could think about to add this function hahahaha. it is really happy to use your auth_analyzer ^=^

**Comment by simioni87** [comment]
Hi Conanjun
Thanks for your input. I like your idea; will be implemented with the next release ;-)

**Comment by Conanjun** [comment]
i have write some code to add this function when token is not existed just add it in getModifiedRequest,may i make a pull request let u review?

**Comment by simioni87** [comment]
Hi Conajun

I just published a new release.

Have fun and regards
