### ISSUE TITLE
Possible bug replacing path values

### ISSUE THREAD

**Issue by Regala** [simioni87/auth_analyzer#12]
Hi @simioni87! 

First of all thank you for this extension - it's really well done. I'm trying to use it for my to day operations but came across a problem replacing path values. 

Say I have a request to :
`GET /api/v1/user/12345/details`
and want to replace it with:
`GET /api/v1/user/admin/details` 

For this to work I was trying to use the static value replacement, e.g.:
![image](https://user-images.githubusercontent.com/1380527/114137454-297e6400-9904-11eb-9814-1b004332c097.png)

This should work right? However, it's turning it into:
![image](https://user-images.githubusercontent.com/1380527/114137635-621e3d80-9904-11eb-92e0-40a210fe8de0.png)
(that is `GET /api/v1/smart/users/12345/admin/1.1`)

Maybe this is a bug or am I doing something wrong?

Thanks!

**Comment by simioni87** [comment]
Hi Regala
No that is not correct. You confound it with "match and replace" which does not work. 
As it is common in API's we use the first section in path to describe the object and followed by the value of the object. In your example the object is "user" and the value is "12345" (or "admin"). Means you want to replace the parameter called "user" with the value "admin". So just type in "user" as parameter name ;-) 
Please see also my example on the Readme page: [https://github.com/simioni87/auth_analyzer#replacement-location](https://github.com/simioni87/auth_analyzer#replacement-location )

Have fun!

**Comment by Regala** [comment]
OOOOOH. You're totally right, and I overlooked the parameter replacement section for some reason 🙈 Thanks!!

**Comment by Regala** [comment]
(p.s. in that particular example in the readme,  `presenet` should be `present`. Thanks again, keep up the good work ❤️ )

**Comment by simioni87** [comment]
Thank you too :) Your issue has disclosed the bug that the path replacement does not correctly work if the parameter value does not ends with a slash. As we see in your example `GET /api/v1/smart/users/12345/admin/1.1`
Will be fixed with the next release.
Thaaanks :)

**Comment by Regala** [comment]
Hi @simioni87 , hope all is well!

I've been doing some more tests with the extension and often a scenario I encounter is this:
* Having a replacement string occurring in multiple places, with different "parameter" names
so e.g. in the url it might be passed as `?organizationId`, where as in the cookie it's under `org=` and in the POST body is `id=`

In this scenarios the easiest thing to do would be to just apply a "match and replace all" rule on the request, regardless of the parameter name. Is this something possible to do at the moment? 

This is a feature I still use heavily on Autorepeater, where the following three options shine:
![image](https://user-images.githubusercontent.com/1380527/119793526-9490f380-bece-11eb-8e0e-959b91e47b8c.png)

Let me know what you think, thanks!
