### ISSUE TITLE
Suggestion: send request to Auth Analyzer even if Analyzer is stopped

### ISSUE THREAD

**Issue by Regala** [simioni87/auth_analyzer#13]
Hi! Sometimes it would be very useful if we could send an item to the Analyzer even if it is stopped. Basically the context menu from Proxy is already there, however we can only send it when the Analyzer is running; which sort of makes sense. However, if there is a session configured, maybe we could send that particular request - it would be processed by the extension, but if you continue the browsing the analyzer would still be paused. 

Does this make sense? Would make easier some flows, e.g. I often only want to test one request from time to time and this way I can send it directly, otherwise I have to go to the extension tab, start it, switch to proxy, send it, switch to extension again and then stop the analyzer 😬

**Comment by simioni87** [comment]
Okay, I agree with you. This just will bring some issues with it. You must have a valid session setup. Otherwise you will be prompted to change your settings before the request will be repeated... I will publish the changes soon.

**Comment by Regala** [comment]
Thanks!!

**Comment by simioni87** [comment]
Hi Regala

I just published a new release with the implementation of this issue. Pull request on the Portswigger Repo is pending. 

Wish you a great weekend and have fun

BR
Simon

**Comment by Regala** [comment]
Thanks!! Will try it out, cheers!
