### ISSUE TITLE
Response Length Difference column

### ISSUE THREAD

**Issue by Regala** [simioni87/auth_analyzer#16]
Hi!

Many times one telltale sign of a authorization issue is when the response length difference from request A and request B is the same (or very similar). This applies when the server responds 200 OK and only differs in the actual response (e.g. json output).

The suggestion is to add a new response length difference column on the main table:
![image](https://user-images.githubusercontent.com/1380527/119794222-403a4380-becf-11eb-9cb0-ab8329e7e98a.png)

This would be super helpful!
To increment this feature and to distinguish from other tools out there, I would allow the ability to set a "offset" of what is tolerable as vulnerable or not. e.g., an offset of 10 bytes means that if the response length difference was between -10 < X < +10 would still be considered an issue.

Thanks!

**Comment by simioni87** [comment]
Hi Regala!

Thanks for your inputs. Will take it into consideration for the next release.

**Comment by simioni87** [comment]
Hi Regala!

I have added a Diff column as well as status setting properties (`Burp Menu -> Auth Analyzer -> Settings`) with the latest beta upload. 

![grafik](https://user-images.githubusercontent.com/37290182/127438373-91e16497-6c32-487e-bc2d-bfbfe4601d86.png)

It will be tested a couple of days until the final release.

**Comment by Regala** [comment]
Wow this looks great! The settings pane is totally different too, many more
options

**Comment by Regala** [comment]
Hi @simioni87, hope all is well 😊 Quick feature suggestion: would it be possible to customize the columns that show up in the main table further? I'm particularly interested in filtering out columns that relate to a session that has been paused (which could happen by "default" when you pause a session). Would make it easier when you pause a particular session in order to make everything more clean! 

Thanks!

**Comment by Regala** [comment]
Oh and I don't know if I mentioned this before (sorry for the spam 🙈) - but would be great to be able to attach some kind of comment on particular lines in the table (say you mark a request and then want to make a note for the future, "this endpoint seems to be vuln to X").

**Comment by simioni87** [comment]
Not sure if I understand correct, but currently you already have the possibility to filter out according to specific statuses (a paused session always has the status N/A)
![grafik](https://user-images.githubusercontent.com/37290182/129432733-ebe48f23-6519-4816-b003-7b09071784bb.png)

The comment feature is a good idea for the next release 👍

**Comment by simioni87** [comment]
Comment Feature added with release 1.1.8
