### ISSUE TITLE
Problems with HTTP/2

### ISSUE THREAD

**Issue by ErwinGeirnaert** [simioni87/auth_analyzer#18]
Hi, during the first use of your nice tool I got problems with a web app using HTTP/2. The modified response always returned an HTTP not supported error. Replaying the same request in Repeater didn't give that error message.

When I disabled HTTP/2 in Project Options - HTTP your tool gave the correct results.

Thanks,

Erwin

**Comment by simioni87** [comment]
Hi Erwin,

This is a known isuue with Burp's API. Please see also issue #15 for more details...
