### ISSUE TITLE
Option to disable URL encoding

### ISSUE THREAD

**Issue by PostalBlab** [simioni87/auth_analyzer#19]
Hi!
I want to replace a parameter value with a string containing a dollar sign "$". Auth Analyzer url encodes the dollar sign with "%24". In my case, the dollar sign is part of a password inside a JSON body, therefore the authentication fails due to the encoding.
It would be awesome to device in the parameter replacement options do enable/disable the url encoding :)

**Comment by simioni87** [comment]
Hello
You are totally right; will be implemented with the next release.
Thanks for this issue!

**Comment by simioni87** [comment]
Implemented with releae 1.1.8
