### ISSUE TITLE
Rework Request/Response View

### ISSUE THREAD

**Issue by aress31** [simioni87/auth_analyzer#2]
Hi @simioni87 

Super extension, just a small suggestion would be to make the request/response view (right panel) less visually heavy. This could be done by using a hierarchy, top level would be request and response and when selecting one of those two options then the different user roles request/response would be displayed.

Also, you should have a look at the Autorize extension which use an expand/collapse view. Also, with the latest version of Burp and the split panel there could be more visually pleasing alternatives to my suggestion. Other than that super work, will keep opening tickets if I can think of other improvements.

Best regards,
Alex

EDIT: This is what I mean by simplifying the view.

![image](https://user-images.githubusercontent.com/11601622/103903083-53e93700-50f3-11eb-9fdd-b37e984a5a76.png)

**Comment by simioni87** [comment]
Hi Alex

Thanks for your inputs. I will take it into consideration.

BR

**Comment by simioni87** [comment]
Hi Alex

I did some massive changes at the message view. Also by using a hirarchy. 

![grafik](https://user-images.githubusercontent.com/37290182/105668750-43e89a00-5ede-11eb-9bef-ecc4dfb189fe.png)

Thanks for your inputs and best regards.

**Comment by aress31** [comment]
Amazing, thanks @simioni87
