### ISSUE TITLE
Feature Request: Null as Parameter Value

### ISSUE THREAD

**Issue by claconsay** [simioni87/auth_analyzer#22]
Hi simioni87,

I have some test cases where I want a specific parameter to be replaced by a null value. 

I tried setting it as the following:
```
param(Static Value)
Value:
```

but the request body(in jSON) becomes:

```
{
"param": ""
}
```
I hope you can also introduce another option called Null as Parameter Value so that the output becomes:

```
{
"param": null
}
```

Thank you so much for this wonderful Burp extension!

**Comment by simioni87** [comment]
Thanks for your input. Will take it into consideration for the next release...

**Comment by simioni87** [comment]
Hi @claconsay 
With the latest release JSON primitive types (null, Boolean and Integers) will be respected and replaced accordingly.
Thanks for your report
