### ISSUE TITLE
XML Parser Error When Opening with Excel

### ISSUE THREAD

**Issue by aress31** [simioni87/auth_analyzer#23]
I am prompted with the following error when trying to open the XML table in Excel:

![image](https://user-images.githubusercontent.com/11601622/135440983-44959cb6-9fe1-4ab8-a312-ef80bfcf0a47.png)

**Comment by simioni87** [comment]
Hi aress31. Sorry for the late response. I am not able to reproduce the issue. Do you have an example export? Did you exported also requests / responses?

**Comment by simioni87** [comment]
Hi @aress31 
I was not able to reproduce your issue but there were some other issues with data export (see #24 ). Those are fixed with the latest release. Would appreciate if you could create a new issue if you problem still exists.
Thanks
