### ISSUE TITLE
[Feature Request] - Filter on request and response body

### ISSUE THREAD

**Issue by t0-git** [simioni87/auth_analyzer#33]
Hello,

Is it possible to add the functionnality to filter on request body (contains or not contains) and response body (contains or not contains) ? 

I think it could be very useful.

**Comment by simioni87** [comment]
Hi,
I totally agree with you, this is already implemented but not released. You can either download and build the project or wait for the next release.

**Comment by simioni87** [comment]
Implemented with the latest release

**Comment by t0-git** [comment]
Very cool! Thank you.
