### ISSUE TITLE
Why's it sending `OPTIONS` request when I'm just specifying headers to delete

### ISSUE THREAD

**Issue by breezemight** [simioni87/auth_analyzer#35]
I'm using the bapp store auth analyzer. I just mentioned some header names to remove and made sure the `exclude http method` option was unchecked, with no other tweaking. Auth analyzer is removing the headers but switching the methods to `OPTIONS` in every request. How do I make it not switch the method?

**Comment by simioni87** [comment]
Since I did not get any reply I assume that my answer helped...
