### ISSUE TITLE
Feature Request: Include Comment Column in Export Table Data

### ISSUE THREAD

**Issue by delatvan** [simioni87/auth_analyzer#37]
First of all amazing plugin! Thank you for the work.

Secondly, I noted that when exporting the data to an HTML or XML document, it is not possible to select and export the "Comment" column. This would be really useful as it could add additional information for the pentester when parsing the data from the file.

**Comment by simioni87** [comment]
Thanks for the issue. Will be considered for the next update.

**Comment by simioni87** [comment]
Implemented with the latest release
