### ISSUE TITLE
Exclude Filetypes match  may bug

### ISSUE THREAD

**Issue by ChenYun4164** [simioni87/auth_analyzer#38]
default setting ，it exclude  .js
![image](https://user-images.githubusercontent.com/45526365/190949311-e186d4e7-c2ca-45c8-ae52-2a39144066ba.png)

but also test .js
![image](https://user-images.githubusercontent.com/45526365/190949321-f31ebf7a-8c05-455f-87e9-cb76db04b278.png)

**Comment by ChenYun4164** [comment]
applogize for late reply.
you can simple to reproduce this 
![image](https://user-images.githubusercontent.com/45526365/191903818-085e9bd6-f154-44b0-9d19-436d61ba888f.png)
![image](https://user-images.githubusercontent.com/45526365/191903908-bb0a071b-8ce9-4cd0-bf47-d8b6c691708a.png)

**Comment by simioni87** [comment]
Okay, but what exactly is the issue with the Auth Analyzer!? You just show an image of the proxy history with a requested js file at your python websever which is not found.

**Comment by simioni87** [comment]
Okay, but what exactly is the issue with the Auth Analyzer!? Is the JS File repeated despite the filter? This is probably because the inferred mime type does not matches JS... --> You have an HTML Response

**Comment by ChenYun4164** [comment]
maybe you can use regex make it more powerful. like this 
![image](https://user-images.githubusercontent.com/45526365/191905788-d38ba6fa-f9ed-4d4b-ad9c-6ee2b80e6b59.png)
simple regex ，dont mind ;-)

**Comment by ChenYun4164** [comment]
![image](https://user-images.githubusercontent.com/45526365/191905964-ee4573e3-3884-422d-b5b3-13ec5259c632.png)

**Comment by ChenYun4164** [comment]
it just request  js file ，auth analyzer no need to request it，because exclude filetype setting.

**Comment by simioni87** [comment]
Depends on what is expected. Actually we don't have a responded JS file. If you would add `html` to your filter it would be filtered. However, I will change the FileTypeFilter and read out only the path for the extension check

`String url = requestInfo.getUrl().getPath().toString().toLowerCase();`

**Comment by ChenYun4164** [comment]
yes its actual i want. : )
