### ISSUE TITLE
More Pending Request Queue

### ISSUE THREAD

**Issue by idlefire** [simioni87/auth_analyzer#39]
What happen?
How do I solve it? Thanks 
![image](https://user-images.githubusercontent.com/18007341/197388127-5bef9751-681b-4767-bc33-54eb209a4704.png)

**Comment by simioni87** [comment]
Assumably you get no response for those requests. The extender api method `makeHttpRequests` has a long default timeout (approx. 2 mins) you must wait for. Did you try to debug it with a logger (e.g. Logger++)??

**Comment by idlefire** [comment]
Yes I confirm from target->http history that requests are all done. I just recreated a session and there is no Pending

**Comment by simioni87** [comment]
It does not make sense to check the proxy history. You must check the repeated requests with a logger. As I told, most likely the server does not responds on the repeated requests; means you have to wait until the timeout to be able to see the requests in the table...
