### ISSUE TITLE
Issues with replacement not working

### ISSUE THREAD

**Issue by AkikoOrenji** [simioni87/auth_analyzer#41]
Using 1.1.13 and have configured a CSRF match which is working fine as  can see the value being populated in the header i've specified.

![image](https://user-images.githubusercontent.com/30274508/216226467-0ab0e5e5-edc0-444e-8fa5-0ff2acaf7cee.png)

The problem is its not replacing the Parameter found in the following Multipart request body. Not shown in the image above is that its just a POST request. 

![image](https://user-images.githubusercontent.com/30274508/216226817-226fa044-6d90-43a0-86ae-364c4b160972.png)

Am i missing something or should the _csrf be replaced with my value  ? \
thanks

**Comment by simioni87** [comment]
You named your parameter `CSRF` but actually it is called `_csrf`

**Comment by AkikoOrenji** [comment]
Thanks for pointing out my mistake.  So if it needs to go into a second parameter just create another with a different name to match that parameter ?

**Comment by simioni87** [comment]
Yes of course. But you can also set the same parameter as an insertion point within the header ($$CSRF$$ --> $$_csrf$$)
