### ISSUE TITLE
Send the edited request before the original request

### ISSUE THREAD

**Issue by theblackturtle** [simioni87/auth_analyzer#6]
When you working with the DELETE/PUT method to delete/update somethings, but if the original sent first, the record is gone so the edited request will fail. It would be nice if auth_analyzer have this option :D

**Comment by simioni87** [comment]
Please see https://github.com/simioni87/auth_analyzer#test-idempotent-operations

**Comment by theblackturtle** [comment]
Oh, I see the "Drop Original Requests". Thanks for the response.
