### ISSUE TITLE
Issues while updating GET parameter

### ISSUE THREAD

**Issue by flo-tuv** [simioni87/auth_analyzer#8]
I am testing an application that is using a session-id provided in a GET parameter (Yeah, should not be used anyway but oh well.. )

I tried to setup a session that should only replace this one URL parameter with a static value (the session of the low-priv user).
I can browse the app but the extension does not seem to replace the URL parameter.

<img width="409" alt="burp_auth_ext_plugin_issue_1" src="https://user-images.githubusercontent.com/49445407/107538608-7247c400-6bc4-11eb-960c-25e2378d3cac.png">

Above is what we intially setup.

Following are the orig. and the request that should have been edited.

<img width="436" alt="burp_auth_ext_plugin_issue_2_mod" src="https://user-images.githubusercontent.com/49445407/107539003-d66a8800-6bc4-11eb-873f-556f7e2b9fbe.png">

The request, where the session-id should have been replaced with the low priv. user's id
<img width="425" alt="burp_auth_ext_plugin_issue_3_mod" src="https://user-images.githubusercontent.com/49445407/107539301-1c275080-6bc5-11eb-9543-27e6d924ff69.png">

What am I doing wrong or is this some weird burp issue ?

**Comment by simioni87** [comment]
Java uses a non-standard scheme for the jsessionid in the URL. The jsessionid is appended to the path with a semicolon and not located at the GET parameters. Therefore the parameter is not recognized and currently there is no way to do so. 
As a workaround you can try to set the jsessionid as a cookie (set `Cookie: jsessionid=FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF` at Header(s) to replace). Java respects both; the jsessionid in the path and as a Cookie. If you are lucky, the Cookie is preferred.

**Comment by flo-tuv** [comment]
Thanks for your reply but this does not seem to work for that particular app, it only honours the id from the URL.

But maybe this could be a feature request for adding this to be able to test apps using that scheme :)

**Comment by simioni87** [comment]
You are right. Will be implemented with the next release ;-)

**Comment by flo-tuv** [comment]
Thanks a ton :)

**Comment by simioni87** [comment]
Hi flo-tuv 
Now added in the latest Release (1.1.5).
Have Fun!
