### ISSUE TITLE
Case Insensitive parameter value

### ISSUE THREAD

**Issue by cos2v-secure** [simioni87/auth_analyzer#9]
Do we already have a support for parameter values which are case insensitive or can we add this feature in the upcoming upgrade? As of now, for any parameter to match, I have to write all the possible cases for the parameter, as can be seen in the screenshot .
<img width="1528" alt="Screenshot 2021-02-24 at 11 00 16 AM" src="https://user-images.githubusercontent.com/79561394/108953163-be990680-7690-11eb-82ca-0728806a6e1f.png">

**Comment by simioni87** [comment]
Currently there is no support for this. Thanks for your input, will be added with the next release.

**Comment by cos2v-secure** [comment]
Thanks @simioni87 for this wonderful extension and quick reply! This extension has made the IDOR testing super intuitive! Looking forward for the next release! Cheers!

**Comment by simioni87** [comment]
Hi cos2v-secure 

I added the feature with the latest release.

![grafik](https://user-images.githubusercontent.com/37290182/112636433-5da25100-8e3d-11eb-8ae5-dc66cbd9d625.png)

Have fun
